### ISSUE TITLE
error at 98% compilation

### ISSUE THREAD

**Issue by pulketo** [xun-project/UltraNote#5]
i got this error:
/root/xxxxx/UltraNote/src/zedwallet/Transfer.cpp:463:11: aviso: "__has_cpp_attribute" no está definido [-Wundef]
       #if __has_cpp_attribute(fallthrough)
           ^
/root/wall2019/UltraNote/src/zedwallet/Transfer.cpp:463:30: error: missing binary operator before token "("
       #if __has_cpp_attribute(fallthrough)

**Comment by UltraNote** [comment]
Which OS?

**Comment by pulketo** [comment]
Nevermind, it compiles fine on gcc 5.3.1, problem was on: 4.8.5.

**Comment by UltraNote** [comment]
Yes, for Centos you need a newer version.
